name: "BookAware (VöBB)"
description: "Get book information from voebb"
version: "0.9.0"
slug: "bookaware_voebb"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  username: null
  password: null
  interval_hors: 12
  topic_prefix: homeassistant/sensor/bookaware_voebb
schema:
  username: str
  password: str
  interval_hours: int
  topic_prefx: str
services:
  - mqtt:need
